version : "3.8"
services:
  phpcontainer:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html 
    depends_on:
      - phpmyadmincontainer   
  dbcontainer:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - ./db_data:/var/lib/mysql  
    ports:
        - "3306:3306"
  
  phpmyadmincontainer:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: phpmyadmincontainer
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - phpmyadmincontainer

